/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package controlador.login;

import com.fasterxml.jackson.core.JsonProcessingException;
import controlador.login.ListaLoginSerializable.LoginSerializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class LoginFrame extends javax.swing.JDialog {

        private final LoginController loginController = new LoginController();
        private final ListaLoginSerializable miListaLogin = new ListaLoginSerializable();
        private final ListaLoginSerializable.LoginSerializable miLogin = miListaLogin.new LoginSerializable();
    /**
     * Creates new form Login
     */
    public LoginFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pack(); // ajustar tamaño del dialogo
        setLocationRelativeTo(null); // centrar en pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsuario = new javax.swing.JLabel();
        lbContra = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btIngresar = new javax.swing.JButton();
        txtAdmin = new javax.swing.JTextField();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbUsuario.setText("Usuario");
        getContentPane().add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lbContra.setBackground(new java.awt.Color(102, 102, 102));
        lbContra.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbContra.setText("Contraseña");
        getContentPane().add(lbContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 260, 30));

        btIngresar.setBackground(new java.awt.Color(0, 204, 0));
        btIngresar.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        btIngresar.setText("Ingresar");
        btIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIngresarMouseClicked(evt);
            }
        });
        getContentPane().add(btIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 160, -1));

        txtAdmin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(txtAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 30));

        imgFondo.setIcon(new javax.swing.ImageIcon("D:\\Users\\Usuario\\Documents\\NetBeansProjects\\Cliente\\src\\main\\java\\idear\\ar\\cliente\\img\\Login.jpg")); // NOI18N
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIngresarMouseClicked
    if (txtAdmin.getText().isEmpty() && txtPass.getPassword() == null ) {
        JOptionPane.showMessageDialog(null, "Debes completar ambos campos");
    } else {
        miLogin.setUsuario(txtAdmin.getText());
        miLogin.setContra(txtPass.getToolTipText());
        
        try {
            loginController.prepararJson(miLogin);
        } catch (JsonProcessingException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            Logger.getLogger(LoginFrame.class.getName()); // cerrar el recurso Logger
        }
    }
    }//GEN-LAST:event_btIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginFrame dialog = new LoginFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIngresar;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel lbContra;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTextField txtAdmin;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

    private void setEchoChar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
